#!/usr/bin/python3
# global_constants.py
"""


    global_constants.py - Constants used in mqtt_lcp applications
            To implement mqtt messaging in a language other than english, edit this file
            and the appropiate config.json files.

The MIT License (MIT)

Copyright 2021 richard p hughes

Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute,
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


"""


class Global(object):
    """ Definition of global literals """
    ACQUIRE = "acquire"
    ACQUIRED = "acquired"
    ACTION = "action"
    ACTIVE = "active"
    ACTIVATE = "activate"
    ACTIVATED = "activated"
    ADD = "add"
    ADDRESS = "address"
    ADDRESS_TYPE = "address-type"
    ALERT = "alert"
    ALL = "all"
    APPLICATION = "application"
    APPROACH = "approach"
    AVAILABLE = "available"
    BAUDRATE = "baudrate"
    BACKUP = "backup"
    BACKUP_PATH = "backup-path"
    BELL = "bell"
    BLANK = "blank"
    BLINK = "blink"
    BLOCK = "block"
    BLOCKS = "blocks"
    BODY = "body"
    BROADCAST = "broadcast"
    BROKER = "broker"
    BUS = "bus"
    BUSY = "busy"
    BUTTON = "button"
    CAB = "cab"
    CAB_ID = "cab-id"
    CENTER = "center"
    CHAR = "char"
    CLEAR = "clear"
    CLICKED = "clicked"
    CLIENT = "client"
    CLOSE = "close"
    CLOSED = "closed"
    CMD = "cmd"
    COL = "col"
    COLS = "cols"
    COLOR = "color"
    COMMAND = "command"
    COMMAND_TOPIC = "command-topic"
    COMPLETE = "complete"
    CONFIG = "config"
    CONNECT = "connect"
    CONNECTED = "connected"
    CONSIST = "consist"
    CONSISTS = "consists"
    COUNT = "count"
    CRITICAL = "critical"
    CURRENT = "current"
    DASHBOARD = "dashboard"
    DATA = "data"
    DATETIME = "datetime"
    DATA_PATH = "data-path"
    DATA_TOPIC = "data-topic"
    DAY = "day"
    DCC = "dcc"
    DCC4PC = "dcc4pc"
    DCC_ACCESSORY = "dcc-accessory"
    DCC_ID = "dcc-id"
    DCC_PP = "dcc++"
    DEACTIVATE = "deactivate"
    DEACTIVATED = "deactivated"
    DEBUG = "debug"
    DELAY = "delay"
    DELETE = "delete"
    DESCRIPTION = "description"
    DETECTED = "detected"
    DEVICE = "device"
    DEVICE_STATE = "device_state"
    DEVICE_TYPE = "device-type"
    DEVICES = "devices"
    DIRECTION = "direction"
    DISCONNECT = "disconnect"
    DISCONNECTED = "disconnected"
    DISPATCHER = "dispatcher"
    DISPLAY = "display"
    DIVERGE = "diverge"
    DT = "dt"
    DESIRED = "desired"
    DOWN = "down"
    DRIVER = "driver"
    DUPLEX = "duplex"
    ECHO = "echo"
    ENTRY = "entry"
    EPOCH = "epoch"
    ENCODER = "encoder"
    ENTERED = "entered"
    ENTRY = "entry"
    EPOCH = "epoch"
    ERROR = "error"
    ERROR_MESSAGE = "error-message"
    EXIT = "exit"
    EXITED = "exited"
    EXPANDER = "expander"
    EXPIRE = "expire"
    FACING = "facing"
    FALSE = "false"
    FAST = "fast"
    FASTCLOCK = "fastclock"
    FILE = "file"
    FORCE = "force"
    FULL = "full"
    FORWARD = "forward"
    FUNCTION = "function"
    FUNCTIONS = "functions"
    GPIO = "gpio"
    GRID = "grid"
    GROUP = "group"
    GROUPS = "groups"
    HEX = "hex"
    HIGH = "high"
    HORN = "horn"
    HOST = "host"
    HOUR = "hour"
    ID = "id"
    IDENTITY = "identity"
    IDLE = "idle"
    IDS = "ids"
    INFO = "info"
    INFO_COMMAND = "info-command"
    IO = "io"
    IO_ADDRESS = "io-address"
    IO_BLOCKS = "io-blocks"
    IO_DATA = "io-data"
    IO_DEVICE = "io-device"
    IO_DEVICE_STATE = "device-state"
    IO_DEVICE_TYPE = "io-device-type"
    IO_METADATA = "io-metadata"
    IO_MUX_ADDRESS = "io-mux-address"
    IO_RESPONSE = "io-response"
    IO_REQUEST = "io-request"
    IO_REQUEST_AND_WAIT = "io-request-and-wait"
    IO_REQUEST_REPEAT = "io-request-repeat"
    IO_SUB_ADDRESS = "io-sub-address"
    IO_SUB_DEVICES = "io-sub-devices"
    IO_TYPE = "io_type"
    INACTIVE = "inactive"
    INCONSISTENT = "inconsistent"
    INTERVAL = "interval"
    I2C = "i2c"
    I2C_BUS_NUMBER = "i2c-bus-number"
    I2C_MESSAGE = "i2c-message"
    IMAGE = "image"
    IMPORT = "import"
    INCONSISTENT = "inconsistent"
    INFO = "info"
    INPUT = "input"
    INVALID = "invalid"
    INVENTORY = "inventory"
    IO_DEVICES = "io-devices"
    ITEMS = "items"
    KEYBOARD = "keyboard"
    KEYPAD = "keypad"
    LABEL = "label"
    LARGE = "large"
    LAYOUT = "layout"
    LAYOUTS = "layouts"
    LEAD = "lead"
    LEAD_SET = "lead-set"
    LEVEL = "level"
    LIGHT = "light"
    LIST = "list"
    LOCATOR = "locator"
    LOCATORS = "locators"
    LOCO = "loco"
    LOCO_BUFFER = "loco-buffer"
    LOCO_ID = "loco-id"
    LOCOS = "locos"
    LOGGER = "logger"
    LOW = "low"
    MAX = "max"
    MAX_LOCOS = "max-locos"
    MAX_SPEEDSTEP = "max-speedstep"
    MEDIUM = "medium"
    MENU = "menu"
    MESSAGE = "message"
    MESSAGES = "messages"
    METADATA = "metadata"
    MIN = "min"
    MINUTES = "minutes"
    MODE = "mode"
    MONTH = "month"
    MQTT = "mqtt"
    MSG = "msg"
    MULTIPLE = "multiple"
    MUX = "mux"
    MUX_ADDRESS = "mux-address"
    MUX_SUB_ADDRESS = "mux-sub-address"
    NAME = "name"
    NETWORK = "network"
    NEXT = "next"
    NO = "no"
    NODE = "node"
    NODES = "nodes"
    NODE_ID = "node-id"
    NORMAL = "normal"
    OCCUPIED = "occupied"
    OFF = "off"
    OK = "ok"
    ON = "on"
    OPEN = "open"
    OPENED = "opened"
    OPTIONS = "options"
    OTHER_TOPICS = "other-topics"
    PAGE = "page"
    PANEL = "panel"
    PANELS = "panels"
    PASSWORD = "password"
    PASS_THROUGH = "pass-through"
    PATH = "path"
    PATHS = "paths"
    PAUSE = "pause"
    PAUSED = "paused"
    PING = "ping"
    PING_TIME = "ping-time"
    PIPE = "pipe"
    POLL = "poll"
    PORT = "port"
    PORTS = "ports"
    PORT_EXPANDER = "port-expander"
    PORT_EXPANDER_RELAY_16 = "port-expander-relay-16"
    PORT_EXPANDER_RELAY_QUAD = "port-expander-relay-quad"
    PORT_ID = "port-id"
    POSITION = "position"
    POWER = "power"
    PRESS = "press"
    PREV = "prev"
    PRODUCT = "product"
    PUBLISH = "pub"
    PUBLIST_DATA = "pub_data"
    PUB_TOPICS = "pub-topics"
    PULSE = "pulse"
    QUERY = " query"
    QUEUE = "queue"
    RAILCOM = "railcom"
    RATIO = "ratio"
    READY = "ready"
    REBOOT = "reboot"
    REBOOT_COMMAND = "reboot-command"
    RECEIVED = "rcv"
    RED = "red"
    REFRESH = "refresh"
    REGISTRY = "registry"
    RELAY_CONTROLLER = "relay-controller"
    RELEASE = "release"
    RELEASED = "released"
    REMOVE = "remove"
    REPORT = "report"
    REPORTED = "reported"
    REQUEST = "request"
    REQ = "req"
    RES = "res"
    RESPOND_TO = "respond-to"
    RESET = "reset"
    RESPONSE = "response"
    RESPONSE_QUEUE = "response_queue"
    RESTART = "restart"
    REVERSE = "reverse"
    REVERSED = "reversed"
    RFID = "rfid"
    RFID_ID = "rfid-id"
    ROOT = "root"
    ROSTER = "roster"
    ROTARY = "rotary"
    ROUTE = "route"
    ROW = "row"
    ROWS = "rows"
    RUN = "run"
    RUNNING = "running"
    SCREEN_SIZE = "screen-size"
    SECONDS = "seconds"
    SELECT = "select"
    SELF = "self"
    SEND = "send"
    SENSOR = "sensor"
    SENSOR_STATES = "sensor-states"
    SENSOR_TYPE = "sensor-type"
    SENSORS = "sensors"
    SERIAL = "serial"
    SERIAL_MODE = "serial-mode"
    SERVER = "server"
    SERVICE = "service"
    SERVO = "servo"
    SERVOS = "servos"
    SERVO_CONTROLLER = "servo-controller"
    SESSION_ID = "session-id"
    SET = "set"
    SET_LEAD = "set-lead"
    SHARE = "share"
    SHARED = "shared"
    SIGNAL = "signal"
    SIGNALS = "signals"
    SIGNAL_TYPE = "signal-type"
    SINGLE = "single"
    SIZE = "size"
    SHUTDOWN = "shutdown"
    SHUTDOWN_COMMAND = "shutdown-command"
    SLOT = "slot"
    SLOTS = "slots"
    SMALL = "small"
    SPEED = "speed"
    SOCKET = "socket"
    START = "start"
    STATE = "state"
    STATES = "states"
    STATIONARY = "stationary"
    STATUS = "status"
    STEAL = "steal"
    STEAL_NEEDED = "steal-needed"
    STEP = "step"
    STOLEN = "stolen"
    STOP = "stop"
    SUB = "sub"
    SUBSCRIBE = "subscribe"
    SUB_ADDRESS = "sub-address"
    SUB_TOPICS = "sub-topics"
    SUPERVISOR = "supervisor"
    SUFFIX = "suffix"
    SWITCH = "switch"
    SWITCHES = "switches"
    SWITCH_TYPE = "switch-type"
    SYSTEM = "system"
    TEXT = "text"
    TEST = "test"
    TIME = "time"
    TIMEOUT = "timeout"
    TIMESTAMP = "timestamp"
    TITLE = "title"
    THROUGH = "through"
    THROTTLE = "throttle"
    THROTTLE_ID = "throttle-id"
    TOGGLE = "toggle"
    TOPIC = "topic"
    TOPICS = "topics"
    TOWER = "tower"
    TRACK = "track"
    THROW = "throw"
    THROWN = "thrown"
    TRUE = "true"
    TOPIC = "topic"
    TRACK = "track"
    TURNOUT = "turnout"
    TURNOUTS = "turnouts"
    TYPE = "type"
    TIMESTAMP = "timestamp"
    UP = "up"
    UNKNOWN = "unknown"
    USB = "usb"
    USB_PRODUCT_ID = "usb-product-id"
    USB_VENDOR_ID = "usb-vendor-id"
    USER = "user"
    VENDOR = "vendor"
    VERSION = "version"
    VERTICAL = "vertical"
    WARNING = "warning"
    WARRANT = "warrant"
    WARRANTS = "warrants"
    WHITE = "white"
    WITHROTTLE = "withrottle"
    WITHROTTLE1 = "withrottle1"
    WITHROTTLE2 = "withrottle2"
    WITHROTTLE3 = "withrottle3"
    WITHROTTLE4 = "withrottle4"
    YEAR = "year"
    YES = "yes"
    MQTT_PUBLISH_JSON = "publish-json"
    MQTT_PUBLISH_IODATA = "publish-iodata"
    MQTT_SUBSCRIBE = "subscribe"
    MQTT_UNSUBSCRIBE = "unsubscribe"
    MQTT_OTHER = "mqtt-other"
    MQTT_REQUEST = "mqtt-request"
    MQTT_REQUEST_SHUTDOWN = "mqtt-request-shutdown"
    MQTT_REQUEST_REBOOT = "mqtt-request-reboot"
    MQTT_REQUEST_BACKUP = "mqtt-request-backup"
    MQTT_REQUEST_TOWER = "mqtt-request-tower"
    MQTT_REQUEST_DISPATCHER = "mqtt-request-dispatcher"
    MQTT_REQUEST_FASTCLOCK = "mqtt-request-fastclock"
    MQTT_REQUEST_SWITCH = "mqtt-request-switch"
    MQTT_REQUEST_SENSOR = "mqtt-request-sensor"
    MQTT_REQUEST_SIGNAL = "mqtt-request-signal"
    MQTT_REQUEST_SIGNAL = "mqtt-request-states"
    MQTT_REQUEST_STATES = "mqtt-request-track"
    MQTT_REQUEST_CAB = "mqtt-request-cab"
    MQTT_REQUEST_NODE = "mqtt-request-node"
    MQTT_RESPONSE = "mqtt-response"
    MQTT_RESPONSE_COMMAND = "mqtt-response-command"
    MQTT_RESPONSE_TOWER = "mqtt-response-tower"
    MQTT_RESPONSE_DISPATCHER = "mqtt-response-dispatcher"
    MQTT_RESPONSE_DISPATCHER_REPORT = "mqtt-response-dispatcher-report"
    MQTT_RESPONSE_DISPATCHER_REPORT_ROSTER = "mqtt-response-dispatcher-report-roster"
    MQTT_RESPONSE_TOWER_REPORT = "mqtt-response-tower-report"
    MQTT_RESPONSE_REGISTRY_REPORT_INVENTORY = "mqtt-response-registry-report-inventory"
    MQTT_RESPONSE_REGISTRY_REPORT = "mqtt-response-registry-report"
    MQTT_RESPONSE_ROSTER_REPORT = "mqtt-response-roster-report"
    MQTT_RESPONSE_INVENTORY_REPORT = "mqtt-response-inventory-report"
    MQTT_RESPONSE_WARRANTS_REPORT = "mqtt-response-warrants-report"
    MQTT_RESPONSE_STATES_REPORT = "mqtt-response-states-report"
    MQTT_RESPONSE_PANELS_REPORT = "mqtt-response-panels-report"
    MQTT_RESPONSE_STATES_REPORT = "mqtt-response-states-report"
    MQTT_RESPONSE_REPORT = "mqtt-response-report"
    MQTT_RESPONSE_FASTCLOCK = "mqtt-response-fastclock"
    MQTT_RESPONSE_SWITCH = "mqtt-response-switch"
    MQTT_RESPONSE_SENSOR = "mqtt-response-sensor"
    MQTT_RESPONSE_TRACK = "mqtt-response-track"
    MQTT_RESPONSE_CAB = "mqtt-response-cab"
    MQTT_RESPONSE_NODE = "mqtt-response-node"
    MQTT_DATA = "mqtt-data"
    MQTT_DATA_PING = "mqtt-data-ping"
    MQTT_DATA_SENSOR = "mqtt-data-sensor"
    MQTT_DATA_SIGNAL = "mqtt-data-signal"
    MQTT_DATA_SWITCH = "mqtt-data-switch"
    MQTT_DATA_BACKUP = "mqtt-data-backup"
    MQTT_DATA_FASTCLOCK = "mqtt-data-fastclock"
    MQTT_DATA_DASHBOARD = "mqtt-data-dashboard"
    MQTT_DATA_BLOCK = "mqtt-data-block"
    MQTT_DATA_LOCATOR = "mqtt-data-locator"
    MQTT_DATA_CAB = "mqtt-data-cab"
    MQTT_MESSAGE = "mqtt-message"
    MQTT_MESSAGE_UNKNOWN = "mqtt-message-unknown"
    MQTT_SENSOR_TYPES = [
        "block", "locator", "sensor", "signal", "switch", "route"
    ]
    SEND_SENSOR_MESSAGE = "send-sensor-message"

    MSG_BACKUP_RECEIVED = "Backup command received"
    MSG_COMPLETED = "...Completed."
    MSG_DESCRIPTION_DASHBOARD = "dashboard of running applications"
    MSG_ERROR_BAD_STATE = "Error - requested state is not valid: "
    MSG_ERROR_BAD_DESIRED = "Error: desired unknown"
    MSG_ERROR_JSON_PARSE = "Error: JSON invalid: "
    MSG_ERROR_NO_DESIRED = "Error: desired missing"
    MSG_ERROR_BAD_PORT_ID = "Error: port id nor recognized"
    MSG_ERROR_SERVO_NOT_KNOWN = "error: requested servo name not known: "
    MSG_ERROR_SERVO_MOVE = "Error: servo movement failed: "
    MSG_ERROR_NO_DCC_ID = "no dcc id specifed: "
    MSG_FULL = "Loco slots full."
    MSG_EXITING = "Exiting."
    MSG_I2C_DATA_RECEIVED = "I2C Data recvd: "
    MSG_I2C_NOT_CONNECTED = "Error, I2C Device Not Connected: "
    MSG_ERROR_JSON_PARSE = "Error: JSON invalid: "
    MSG_KEYBOARD_RECEIVED = "Keyboard Input Received: "
    MSG_NEW_SWITCH = "new turnout req received: "
    MSG_REBOOT_RECEIVED = "Reboot command received"
    MSG_REQUEST_MSG_RECEIVED = "Request message recvd: "
    MSG_RESPONSE_RECEIVED = "Response message recvd: "
    MSG_SEND_SERIAL = "Sending Serial message: "
    MSG_SERIAL_RECEIVED = "Serial Input received: "
    MSG_SEND_SERIAL_WAIT = "Send / Wait Serial message: "
    MSG_SHUTDOWN_PUBLISHED = "Shutdown broadcast published ..."
    MSG_SHUTDOWN_RECEIVED = "Shutdown command received"
    MSG_STARTING = "Starting..."
    MSG_STEAL = "Loco is use by another throttle, you must steal it."
    MSG_UNKNOWN_REQUEST = "Unknown Request message recvd: "
    MSG_UNKNOWN_NODE = "Unknown Node in message recvd: "
    MSG_NEW_SWITCH = "new turnout req received: "
    MSG_ERROR_BAD_STATE = "Error: requested state is not valid: "
    MSG_ERROR_SERVO_NOT_KNOWN = "Error: requested servo name not known: "
    MSG_ERROR_SERVO_MOVE = "Error: servo movement failed: "
    MSG_WAIT = "Waiting to exit ..."

    DRIVER_INPUT = "driver-input"
    DRIVER_SEND = "driver-send"
    DRIVER_WRITE = "driver-write"
    DRIVER_SEND_AND_RESPOND = "driver-send-and-respond"
    DRIVER_RESPONSE = "driver-response"
    DRIVER_CONNECT = "driver-connect"
    DRIVER_CLOSE = "driver-close"
    DRIVER_ERROR = "driver-error"
    DRIVER_READ = "driver-read"

    DEVICE_INPUT = "device-input"
    DEVICE_SEND = "device-send"
    DEVICE_WRITE = "device-write"
    DEVICE_SEND_AND_RESPOND = "device-send-and-respond"
    DEVICE_RESPONSE = "device-response"
    DEVICE_CONNECT = "device-connect"
    DEVICE_CLOSE = "device-close"
    DEVICE_ERROR = "device-error"
    DEVICE_READ = "device-read"

    DEVICE_INPUT_BLOCK_DATA = "serial-device-input-block-data"
    DEVICE_INPUT_RAILCOM_DATA = "serial-device-input-railcom-data"

    LOG_LEVEL_CRITICAL = 50
    LOG_LEVEL_ERROR = 40
    LOG_LEVEL_WARNING = 30
    LOG_LEVEL_INFO = 20
    LOG_LEVEL_DEBUG = 10
    LOG_LEVEL_NOSET = 0

    def __init__(self):
        pass

    @classmethod
    def generate_reversed_list(cls):
        """ generate a dictionary of Global values with value as the key """
        global_consts = Global()
        attributes = dir(global_consts)
        reversed_consts = {}
        for _i, value in enumerate(attributes):
            # print(type(value))
            if (isinstance(value, str) and not value.startswith("_")):
                attr_value = getattr(global_consts, value)
                if isinstance(attr_value, str):
                    # print(" ... "+str(type(attr_value)))
                    reversed_consts.update({attr_value: value})
        return reversed_consts
